### ISSUE TITLE
在线版首页出错了

### ISSUE THREAD

**Issue by worldask** [xingbofeng/douban-movie#1]
http://www.angryzhangzhe.cn:3000/
返回错误400

**Comment by worldask** [comment]
本地进入 server 目录运行，提示 '这个页面不存在'

**Comment by xingbofeng** [comment]
1. 在线版400是由于所有请求经过我的服务器进行转发，而豆瓣的访问限制是每分钟40次，因而本地体验更佳！
2. 本地进入server目录需要node index.js启动，因本项目使用history路由。需要开启服务端配合。
3. 联系本地使用npm run dev启动项目访问。
