### ISSUE TITLE
npm bugs phantomjs-prebuilt

### ISSUE THREAD

**Issue by ZebraSu** [xingbofeng/douban-movie#2]
It cant work on my windows System,Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'

**Comment by xingbofeng** [comment]
you can see if it is the question about 
CRLF  http://stackoverflow.com/questions/37826449/expected-linebreaks-to-be-lf-but-found-crlf-linebreak-style-in-eslint-using

**Comment by xingbofeng** [comment]
besides, you can try to `rm -rf node_modules` and `cnpm install`

**Comment by ZebraSu** [comment]
Thank for rep,i try another way to settle that.it works well for me!
http://stackoverflow.com/questions/40992231/failed-at-the-phantomjs-prebuilt2-1-13-install-script-node-install-js
